# Generated by Django 5.1.1 on 2024-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buystocks", "0002_stockorder_executed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliostock",
            name="average_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="portfoliostock",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
