# Generated by Django 5.1.1 on 2024-10-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buystocks", "0003_alter_portfoliostock_average_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliostock",
            name="average_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="portfoliostock",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
